name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 10

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
        timeout-minutes: 10

      - name: Install dependencies
        env:
          PIP_EXTRA_INDEX_URL: https://aa:${{ secrets.PYPI_PASSWORD }}@pypi.autoactuary.com/simple
        run: |
          python -m pip install -c ci-constraints.txt .
        timeout-minutes: 10

      - name: Test
        run: |
          python -m unittest
        timeout-minutes: 60
